### ISSUE TITLE
Index error 

### ISSUE THREAD

**Issue by shbnm21** [csmliu/STGAN#23]
hello,
i have downloaded trained model and trying to test it on google colab but i am getting index error in data file
i have used only 637 images from 182000 to 182637
  img_paths = [img_paths[i-1] for i in im_no]
IndexError: list index out of range

**Comment by csmliu** [comment]
You can try to change 'test' to 'val' in https://github.com/csmliu/STGAN/blob/ce592029501724fddc47019cd2b25624ad166c1f/test.py#L109

**Comment by shbnm21** [comment]
Thank u so much for quick reply .
I will change it and will let u know.

**Comment by shbnm21** [comment]
getting same error
In readme.md u have mentioned that while testing images should no smaller than 182638 
so i added two images in dataset to test and use following command
!python test.py --experiment_name 128 --test_int 1.0 --dataroot DATAROOT --img 197880 197882
and ouput is 



WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Using selected images: [197880, 197882]
WARNING:tensorflow:From /content/gdrive/My Drive/Colab Notebooks/STGAN/tflib/utils.py:13: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /content/gdrive/My Drive/Colab Notebooks/STGAN/tflib/utils.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-19 07:09:34.647258: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-10-19 07:09:34.647471: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2d712c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-19 07:09:34.647506: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    te_data = data.Celeba(dataroot, atts, img_size, 1, part='val', sess=sess, crop=not use_cropped_img, im_no=img)
  File "/content/gdrive/My Drive/Colab Notebooks/STGAN/data.py", line 191, in __init__
    img_paths = [img_paths[i-1] for i in im_no]
  File "/content/gdrive/My Drive/Colab Notebooks/STGAN/data.py", line 191, in <listcomp>
    img_paths = [img_paths[i-1] for i in im_no]
IndexError: list index out of range



and when i use folloing command
!python test.py --experiment_name 128  --test_int 1.0

i get different error

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Using selected images: None
WARNING:tensorflow:From /content/gdrive/My Drive/Colab Notebooks/STGAN/tflib/utils.py:13: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /content/gdrive/My Drive/Colab Notebooks/STGAN/tflib/utils.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-19 07:11:04.866549: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2019-10-19 07:11:04.866759: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x320b2c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-19 07:11:04.866791: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.read_file is deprecated. Please use tf.io.read_file instead.

Traceback (most recent call last):
  File "test.py", line 109, in <module>
    te_data = data.Celeba(dataroot, atts, img_size, 1, part='val', sess=sess, crop=not use_cropped_img, im_no=img)
  File "/content/gdrive/My Drive/Colab Notebooks/STGAN/data.py", line 216, in __init__
    repeat=repeat)
  File "/content/gdrive/My Drive/Colab Notebooks/STGAN/data.py", line 64, in disk_image_batch_dataset
    map_func_, num_threads, shuffle, buffer_size, repeat)
  File "/content/gdrive/My Drive/Colab Notebooks/STGAN/data.py", line 19, in batch_dataset
    dataset = dataset.map(map_func, num_parallel_calls=num_threads)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1913, in map
    self, map_func, num_parallel_calls, preserve_cardinality=False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3472, in __init__
    use_legacy_function=use_legacy_function)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2713, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1853, in _get_concrete_function_internal
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 1847, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2147, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2038, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2707, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2652, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:

    /content/gdrive/My Drive/Colab Notebooks/STGAN/data.py:57 map_func_  *
        return map_func(*parse_func(*args))
    /content/gdrive/My Drive/Colab Notebooks/STGAN/data.py:51 parse_func  *
        img = tf.read_file(path)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_io_ops.py:626 read_file
        "ReadFile", filename=filename, name=name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py:551 _apply_op_helper
        (prefix, dtypes.as_dtype(input_arg.type).name))

    TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

**Comment by CastellanLiu** [comment]
Are you using Tensorflow 2.0? I don't think that my code is compatible with TF 2.0.

**Comment by shbnm21** [comment]
I am testing your code on google colab and they have default version of tensorflow is
1.15.0-rc3

**Comment by shbnm21** [comment]
Hello,
In readme u mentioned to put images and attribute file in DATAROOT folder

but in data.py path is given like this
 data = Celeba('D:/Datasets/CelebA/Img', atts, 128, 32, part='val')

and in train.py default path is given as
dataroot_default = '/data/Datasets/CelebA/Img'

Also u mentioned to follow setting of attgan
in attgan they have placed images and attribute file in data folder

so i am confused 

can u tell me where to actually keep images and attribute file

**Comment by csmliu** [comment]
1. I ran the code on windows and linux, so you could feel free to set your own DATAROOT, like
`python train.py --experiment_name 128 --dataroot D:/Datasets/CelebA/Img`
2. I said that you could follow AttGAN to prepare the images (such as 384x384 images), yet for correctly placing the images and label file, you should follow https://github.com/csmliu/STGAN/blame/master/README.md#L27.
To make it clear, the structure of my data folder is (taking `D:/Datasets/CelebA/Img` as an example):
D:/Datasets/CelebA/Img/
　| - img_align_celeba/
　　| - 000001.jpg
　　| - 000002.jpg
　　| - ...
　　| - 202599.jpg
　| - list_attr_celeba.txt
Then, you can set dataroot as `D:/Datasets/CelebA/Img`

**Comment by shbnm21** [comment]
Ok ,got it.

Thank you

**Comment by csmliu** [comment]
I'm closing this issue, if you have any other questions, please feel free to reopen it or comment below, or open a new issue if unrelated to this one.

**Comment by shbnm21** [comment]
hii
I was successfully able to test the project on windows.

thank u
