### ISSUE TITLE
Keep getting errors when training

### ISSUE THREAD

**Issue by XijieJiao** [csmliu/STGAN#38]
The images in img_align_celeba are of 178*218. I tried to train the network for testing 128*128 images. I resized and aligned the images in the dataset. I trained the network using 'python train.py --experiment_name 128'.
However, I keep getting errors as below. 

Traceback (most recent call last):
  File ".local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File ".local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File ".local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [height must be >= target + offset.]
	 [[Node: crop_to_bounding_box/Assert_1/Assert = Assert[T=[DT_STRING], summarize=3](crop_to_bounding_box/GreaterEqual_1, crop_to_bounding_box/Assert_1/Assert/data_0)]]
	 [[Node: IteratorGetNext_1 = IteratorGetNext[output_shapes=[[64,128,128,3], [64,13]], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "STGAN/train.py", line 312, in <module>
    xa_sample_ipt, a_sample_ipt = val_data.get_next()
  File "STGAN/data.py", line 93, in get_next
    return self._sess.run(self._batch_op)
  File "/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File ".local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File ".local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [height must be >= target + offset.]
	 [[Node: crop_to_bounding_box/Assert_1/Assert = Assert[T=[DT_STRING], summarize=3](crop_to_bounding_box/GreaterEqual_1, crop_to_bounding_box/Assert_1/Assert/data_0)]]
	 [[Node: IteratorGetNext_1 = IteratorGetNext[output_shapes=[[64,128,128,3], [64,13]], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator_1)]]
Traceback (most recent call last):
  File "STGAN/train.py", line 381, in <module>
    save_path = saver.save(sess, '%s/Epoch_(%d)_(%dof%d).ckpt' % (ckpt_dir, epoch, it_in_epoch, it_per_epoch))
NameError: name 'it_in_epoch' is not defined

Process finished with exit code 1

I thought it might be the problem with changing the input image. I went back to your original dataset and still met the same errors. 
Could you please give me some suggestions about my problems? Thank you.

**Comment by csmliu** [comment]
Hi there,
According to the error information (`NameError: name 'it_in_epoch' is not defined`), the error may be caused by an undefined variable `it_in_epoch`, however in my code it is defined [in this line](https://github.com/csmliu/STGAN/blob/master/train.py#L330). Could you check whether have you removed this line?
Best,
Ming
