### ISSUE TITLE
i met a mistack when i run the sourcecode as follwing

### ISSUE THREAD

**Issue by TLZS** [csmliu/STGAN#58]
img_paths = img_paths[:182000]
UnboundLocalError: local variable 'img_paths' referenced before assignment

**Comment by CastellanLiu** [comment]
Sorry, I didn't find this statement in the code, could you provide more details about your question?

**Comment by TLZS** [comment]
Thanks for your replay,the whole mistake as follwing:

   Traceback (most recent call last):
  File "train.py", line 161, in <module>
    tr_data = data.Celeba(dataroot, atts, img_size, batch_size, part='train', sess=sess, crop=crop_)
  File "D:\he\STGAN-master\data.py", line 201, in __init__
    img_paths = img_paths[:182000]
UnboundLocalError: local variable 'img_paths' referenced before assignment

**Comment by CastellanLiu** [comment]
Please check your dataset, see https://github.com/csmliu/STGAN/blob/master/data.py#L157-L160
